const molduras = [
  {
    dominio: "moldura-1",
    titulo: "Moldura 1",
    styleText: {
      translateX: 540,
      translateY: 325,
      rotate: -8,
      maxWidth: 820,
      fontSize: 92,
      minFontSize: 42,
      color: "#00522d",
      backgroundColor: "#ffd400",
    },
    imagens: {
      figureText: "./imagens/moldura-texto-1.png",
      thumbnailText: "./imagens/moldura-texto-1.png",
      figurePhoto: "./imagens/moldura-imagem-1.png",
      thumbnailPhoto: "./imagens/moldura-imagem-1.png",
    },
  },
  {
    dominio: "moldura-2",
    titulo: "Moldura 2",
    styleText: {
      translateX: 540,
      translateY: 270,
      maxWidth: 800,
      fontSize: 92,
      minFontSize: 42,
      color: "#00522d",
      backgroundColor: "#ffd400",
    },
    imagens: {
      figureText: "./imagens/moldura-texto-2.png",
      thumbnailText: "./imagens/moldura-texto-2.png",
      figurePhoto: "./imagens/moldura-imagem-2.png",
      thumbnailPhoto: "./imagens/moldura-imagem-2.png",
    },
  },
  {
    dominio: "moldura-3",
    titulo: "Moldura 3",
    styleText: {
      translateX: 540,
      translateY: 210,
      rotate: -8,
      maxWidth: 780,
      fontSize: 92,
      minFontSize: 42,
      color: "#ffd400",
      backgroundColor: "#00782f",
    },
    imagens: {
      figureText: "./imagens/moldura-texto-3.png",
      thumbnailText: "./imagens/moldura-texto-3.png",
      figurePhoto: "./imagens/moldura-imagem-3.png",
      thumbnailPhoto: "./imagens/moldura-imagem-3.png",
    },
  },
  {
    dominio: "moldura-4",
    titulo: "Moldura 4",
    styleText: {
      translateX: 540,
      translateY: 320,
      maxWidth: 800,
      fontSize: 92,
      minFontSize: 42,
      color: "#0b2a7a",
      backgroundColor: "#ffd400",
    },
    imagens: {
      figureText: "./imagens/moldura-texto-4.png",
      thumbnailText: "./imagens/moldura-texto-4.png",
      figurePhoto: "./imagens/moldura-imagem-4.png",
      thumbnailPhoto: "./imagens/moldura-imagem-4.png",
    },
  },
  {
    dominio: "moldura-5",
    titulo: "Moldura 5",
    styleText: {
      translateX: 540,
      translateY: 270,
      rotate: -5,
      maxWidth: 780,
      fontSize: 92,
      minFontSize: 42,
      color: "#ffd400",
      backgroundColor: "#1b3a8f",
    },
    imagens: {
      figureText: "./imagens/moldura-texto-5.png",
      thumbnailText: "./imagens/moldura-texto-5.png",
      figurePhoto: "./imagens/moldura-imagem-5.png",
      thumbnailPhoto: "./imagens/moldura-imagem-5.png",
    },
  },
];
